# Generated by Django 3.0.3 on 2020-02-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200228_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
